//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devamsizlik
    {
        public int id { get; set; }
        public System.DateTime tarih { get; set; }
        public bool durum { get; set; }
        public int ogrenci_id { get; set; }
    }
}
