//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sah_obs_basicEntities : DbContext
    {
        public sah_obs_basicEntities()
            : base("name=sah_obs_basicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dersler> Derslers { get; set; }
        public virtual DbSet<Devamsizlik> Devamsizliks { get; set; }
        public virtual DbSet<Duyurular> Duyurulars { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Notlar> Notlars { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Yetkiler> Yetkilers { get; set; }
    }
}
